spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Ephraim001?
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate: 
       format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect    